### ISSUE TITLE
BUGGAR

### ISSUE THREAD

**Issue by Lovexd16** [Lovexd16/inlamning1grupp5#93]
~~1. När man skapat ett konto kommer man inte till riktiga kontosidan~~
~~2. När man subscribar kan man skriva fel lösenord men ändå komma vidare~~
~~3. Betalsidan för att subscriba laddade inte ordentligt, men blev subscribad ändå~~
~~4. När man editar kontot men inte ändrar något blir allt "undefined"~~
~~5. Home pagen visas inte på rätt sätt efter jag gick ut från konto sidan~~
~~6. Kan skriva fel lösenord när jag raderar konto och det går fortfarande vidare, men kontot raderas inte~~
~~7. När jag raderat mitt konto står det fortfarande "memberpage & logout", händer inget när jag klickar på dem~~
~~8. Fel felmeddelande när jag skapar konto med bara en bokstav på allt~~
~~9. Podcasts och merch laddar i olika ordning~~
~~10. Member page & logout får inte sträck under sig eller pointer mus vid hover~~

**Comment by D-Hankin** [comment]
finished and merged
